default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: gplibrary_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gplibrary_test
  pool: 5
